name: linux

on: [push]

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install required packages
        run: apt-get update && apt-get install -y git python

      - name: Install dotfiles
        run: bash ${GITHUB_WORKSPACE}/install
