name: macos

on: [push]

jobs:
  macos-test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install required packages
        run: brew install git

      - name: Install dotfiles
        run: bash ${GITHUB_WORKSPACE}/install
